sudo: required
services:
  - docker
before_install:
  # Encrypted gcloud Account-Service.json file
  - openssl aes-256-cbc -K $encrypted_8685b91d5668_key -iv $encrypted_8685b91d5668_iv -in account-service.json.enc -out account-service.json -d
  # Install & update gcloud-cli
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json